server:
  servlet:
    context-path: /notification-service
  port: 8083

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: fds.karanda@gmail.com
    password: bestuser1!
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true

app:
  templates:
    create:
      path: templates/create.ftl
      subject: Новый заказ
    delivery:
      path: templates/delivery.ftl
      subject: Заказ передан в доставку
    done:
      path: templates/done.ftl
      subject: Заказ доставлен
    paid:
      path: templates/paid.ftl
      subject: Заказ оплачен
